### ISSUE TITLE
Brief comments on EAD4 rev

### ISSUE THREAD

**Issue by vns2** [SAA-SDT/eas-schemas#131]
## Creator of issue

Ruth Kitchin Tillman
ruthtillman@gmail.com

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: I'm attaching a document with notes on a handful of things which I considered worthy of comment: About half the comments are positive. For those, I focused on things I'd prefer to stay the way they are in this draft or only undergo very light revision if you come up with better ideas. Another suggestion is specific to creating documentation later on. Big picture, I think it's going in a great direction, like the soft alignment with/alternative to RiC, and think this improves (mostly, see one comment) on previous support for encoding data which could be extracted to create linked data.

[EAD4_Comments_Tillman.docx](https://github.com/user-attachments/files/16398577/EAD4_Comments_Tillman.docx)

**Comment by kerstarno** [comment]
Adding the general comments from the Word document provided by @ruthtillman here. Comments that require further review have been separated out into new issues. With this separation, this issue here will be closed. 

**Overall simplification**
I think the overall trend toward simplification and reuse has been a good one. I was a bit nervous when I saw you were doing a revision, but I think this is significant enough and introduces enough positive changes to merit being done. 
Breaking apart `<control>` and the new `<findAidDesc>` made sense to me.

**agent**
Big picture: I really really like this change! It fulfills the goal of extensibility! It's fairly simple! It seems to support the inclusion of diverse types of agents and a linked data-forward model.
_Additional comments will be dealt with in issue #134 and https://github.com/SAA-SDT/EAS-TagLibraries/issues/146._

**Removal of individual formatting options**
Overall, this seems like a wise choice to me and I'm not going to suggest you revert it.
_Additional comments will be dealt with in issue #118 and in issue https://github.com/SAA-SDT/EAS-TagLibraries/issues/147._

**`@valueURI`, `@vocabularySource`, `@vocabularySourceURI`**
I am really glad to see these incorporated from EAD4. I think they are a robust set of options for the inclusion of data which could be extracted and modeled as linked data.
